# Compose file version
version: "3"

# services
services:
  reverse-proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - 80:80    

  nodejs1:
    image: docker/dockernodejs1
    container_name: nodejs1
    ports:
      - 81:80
  nodejs2:
    image: docker/dockernodejs2
    container_name: nodejs2
    ports:
      - 82:80
